{{- if .Values.bot.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freqtrade-webserver-{{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: freqtrade-webserver-{{ .Release.Namespace }}
  template:
    metadata:
      labels:
        app: freqtrade-webserver-{{ .Release.Namespace }}
    spec:
      # nodeName: {{ .Values.kubernetes.nodeNameBackTestingResultsReeader }} # pool-dersalvador-y5w2t # pool-dersalvador-ylyw0
      containers:
      - name: freqtrade-webserver-{{ .Release.Namespace }}
        image: {{ .Values.image.base }}:{{ .Values.image.tag }}
        command:
        - freqtrade
        args:
        - webserver
{{- if .Values.bot.debug }}
        - {{ .Values.bot.debuglevel }}
{{- end }}
        - --config
        - /freqtrade/config/config.json
        - --config
        - /freqtrade/configcreds/configcreds.json
        - --log-file 
        - /tmp/freqtrade-webserver.log
        - --data-dir
        - /freqtrade/user_data/data
        volumeMounts:
        - name: backtesting-data
          mountPath: /freqtrade/user_data/data
        - name: strategies
          mountPath: /freqtrade/user_data/strategies
        - name: extra-strategies
          mountPath: /freqtrade/user_data/extra_strategies
        - name: configcreds
          mountPath: /freqtrade/configcreds
        - name: config
          mountPath: /freqtrade/config
        - name: sqlite
          mountPath: /sqlite
        ports:
        - name: api
          containerPort: {{ .Values.config.api_server.listen_port }}
      imagePullSecrets:
      - name: do-dersalvador-registry
      volumes:
      - name: backtesting-data
        persistentVolumeClaim:
          claimName: freqtrade-backtesting-data
      - name: extra-strategies
        persistentVolumeClaim:
          claimName: freqtrade-extra-strategies
      - name: configcreds
        configMap:
          name: freqtrade-config-creds-{{ .Release.Namespace }}
      - name: config
        configMap:
          name: freqtrade-config-{{ .Release.Namespace }}
      - name: strategies
        configMap:
          name: freqtrade-strategies-{{ .Release.Namespace }}
      - name: sqlite
        persistentVolumeClaim:
          claimName: freqtrade-sqlite
---
{{- end }}
