---
kubernetes:
  nodePort: 32325

configcreds:
  # trading_mode: futures
  # margin_mode: isolated
  bot_name: freqtrading-binance-larissa
  timeframe: 5m
  trading_mode: spot
  stake_amount: unlimited  
  exchange:
    name: binance
    # API Futures 
    key: eU4J1XrpnGLKNpxjSE16AIPnxkjOVCp6twsieeOOng9g97zvICIYbChITn0nCwe7
    secret: qoetTs4vyUSouAG34yI5s6DVdcIPl7aJ39hftP1xEukPzuoXCCirgvOe07MI0wsy
    # API Spot
    # key: B7M26i11tIFNDPGcXG8Yu3ZOoI6eB1LcOP3FMpXTgI8T7ejICD9yYxMGMZ1kFN0y
    # secret: MAopXKz9eJMyN6vL6bxO57YyqeHW6fWISaFtz4CdWWCjHgA8gFBKIA5hqFDFePqy
  telegram:
    enabled: true
    token: "6607555119:AAGqoNPH-3m1SECXrPeZdtRDgTuy5988BN0"
    chat_id: "6456658723"
    # pairlists:
      # - method: StaticPairList
    #  - method: RemotePairList
    #    number_assets: 50
    #    pairlist_url: https://remotepairlist.com?q=422f8201e9d8a16b
    #    mode: whitelist
    #  - method: RemotePairList
    #    number_assets: 50
    #    mode: blacklist
    #    pairlist_url: https://remotepairlist.com?q=8fc6625b0bc79a51
    #  - method: AgeFilter
    #    min_days_listed: 30
    #  - method: PriceFilter
    #    low_price_ratio: 0.003
    #  - method: SpreadFilter
    #    max_spread_ratio: 0.005
    #  - method: RangeStabilityFilter
    #    lookback_days: 3
bot:
  debug: false
  debuglevel: -vvv
  enabled: true
  strategy_name: NNTC
  pvc_size: 1Gi
  freqaimodel: LightGBMRegressor
