configcreds:
  trading_mode: futures
  margin_mode: isolated
  max_open_trades: 10
  available_capital: 1500
  bot_name: freqtrading-binance-futures
  stake_amount_type: quote_currency
  pair_blacklist: ["FLR/USDT", "(BNB)/.*" ]
  pair_whitelist: ["BTC/USDT:USDT","ETH/USDT:USDT","YFI/USDT:USDT","SOL/USDT:USDT","MKR/USDT:USDT","BNB/USDT:USDT","BCH/USDT:USDT","LTC/USDT:USDT","TRB/USDT:USDT","AVAX/USDT:USDT","LINK/USDT:USDT","AAVE/USDT:USDT","ORDI/USDT:USDT","ILV/USDT:USDT","BTCDOM/USDT:USDT","XMR/USDT:USDT","INJ/USDT:USDT","TIA/USDT:USDT","SSV/USDT:USDT","ETC/USDT:USDT","UNFI/USDT:USDT","ATOM/USDT:USDT","DEFI/USDT:USDT","AXS/USDT:USDT","COMP/USDT:USDT","RUNE/USDT:USDT","EGLD/USDT:USDT","FOOTBALL/USDT:USDT","GAS/USDT:USDT","DOT/USDT:USDT","UNI/USDT:USDT","QNT/USDT:USDT","APT/USDT:USDT","FIL/USDT:USDT","GMX/USDT:USDT","WLD/USDT:USDT","DYDX/USDT:USDT","KSM/USDT:USDT","APE/USDT:USDT","BSV/USDT:USDT","NEO/USDT:USDT","ZEC/USDT:USDT","BLUR/USDT:USDT","RNDR/USDT:USDT","XRP/USDT:USDT","DASH/USDT:USDT","MATIC/USDT:USDT","OP/USDT:USDT","NEAR/USDT:USDT","CYBER/USDT:USDT"]
  telegram:
    enabled: true
    token: "6271542729:AAFvduNLbNHDhi2_381mqBymKZomA1TAL7I"
    chat_id: "5711830404"        
  entry_pricing:
    price_side: other
    use_order_book: true
    order_book_top: 1
    price_last_balance: 0
    check_depth_of_market:
      enabled: false
      bids_to_ask_delta: 1
  exit_pricing:
    price_side: other
    use_order_book: true
    order_book_top: 1    
  dataformat_ohlcv: feather
  dataformat_trades: feather  
  download_trades: false
  dry_run: false
  dry_run_wallet: 4000
  stake_amount: unlimited
  position_adjustment_enable: true
  exchange:
    ccxt_config:
      enableRateLimit: true
      rateLimit: 2500
      options:
        defaultType: future
        leverage: 100
    ccxt_async_config:
      enableRateLimit: true
      rateLimit: 2500
      options:
        defaultType: future
        leverage: 100
    name: binance
    key: ZJ8HMz2H5G1HMqcZh5yIJmoCVcWrYZLp9ZUqMhhSlb6mdJnzjUkNrdN8rJ4Zw7ro
    secret: Q37TvH7ORApOdkNl7IYvLhBVjxhcGzGagvH86jrJCHEtTeUsxPZGlPTe8wYpqWfO
  pairlists:
  - method: RemotePairList
    number_assets: 50
    pairlist_url: https://remotepairlist.com?q=422f8201e9d8a16b
    mode: whitelist
    processing_mode: append
    refresh_period: 600
    keep_pairlist_on_failure: true
    read_timeout: 120
  - method: RemotePairList
    number_assets: 50
    mode: blacklist
    pairlist_url: https://remotepairlist.com?q=08f55c8e02529216
    processing_mode: append
    refresh_period: 600
    keep_pairlist_on_failure: true
    read_timeout: 120
  - method: AgeFilter
    min_days_listed: 30
  - method: PriceFilter
    low_price_ratio: 0.003
  - method: SpreadFilter
    max_spread_ratio: 0.005
  - method: RangeStabilityFilter
    lookback_days: 3
    min_rate_of_change: 0.03
    refresh_period: 1800
  - method: ShuffleFilter
bot:
  debug: false
  debuglevel: -vvv
  enabled: true
  strategy_name: AdxSmasS_v7
  pvc_size: 1Gi
  freqaimodel: LightGBMRegressor 
