---
kubernetes:
  nodePort: 32325

configcreds:
  stake_amount: 50
  # trading_mode: futures
  # margin_mode: isolated
  bot_name: freqtrading-binance-larissa
  # pairlists:
  #   - method: RemotePairList
  #     number_assets: 50
  #     pairlist_url: https://remotepairlist.com?q=175979476d5fc223
  #     processing_mode: append
  #     mode: whitelist
  #     sort_key: quoteVolume
  #     refresh_period: 900
  #     keep_pairlist_on_failure: true
  #     read_timeout: 60
  #   - method: RemotePairList
  #     number_assets: 50
  #     pairlist_url: https://remotepairlist.com?q=ac822c0252729ed2
  #     processing_mode: append
  #     mode: blacklist
  #     sort_key: quoteVolume
  #     refresh_period: 900
  #     keep_pairlist_on_failure: true
  #     read_timeout: 60  
  exchange:
    name: binance
    key: Zp2MxtUwPPofPylEiAhO8sR9DJlWycMVnfvnZTSdalSmkx8g9BNxE7j2g0YJC0OY
    secret: JRJfHc1o3tdKXy384M1PUFPGtpRFEmhVTd0DNgOmzj17Oqrq74kyM5Ltj6iSQpVX
  telegram:
    enabled: true
    token: "6607555119:AAGqoNPH-3m1SECXrPeZdtRDgTuy5988BN0"
    chat_id: "6456658723"
bot:
  debug: false
  debuglevel: -vvv
  enabled: true
  strategy_name: NNTC
  pvc_size: 1Gi
  freqaimodel: LightGBMRegressor
