---
kubernetes:
  nodePort: 32336

configcreds:
  dry_run: true
  dry_run_wallet: 500000000  
  available_capital: 500000000
  #stake_amount: 50
  bot_name: freqtrading-binance-michael-dry1
  exchange:
    name: binance
    key: b3r35QxZ6z8PKS7vFSoJztdTwI4mQJ1owCBmp08pjKj1FQWhFFxvFZ9yqStfpGwm
    secret: tHwYon2naTO6111rCo3c6yv84szDFFsaovNnf9eUY9FYl5Ub07c9IuZ8WTZx4uov
  telegram:
    enabled: false
    token: "6271542729:AAFvduNLbNHDhi2_381mqBymKZomA1TAL7I"
    chat_id: "5711830404"
  freqai:
    enabled: false
    fit_live_predictions_candles: 300
    purge_old_models: true
    train_period_days: 30
    identifier: unique-id
    live_retrain_hours: 1
    feature_parameters:
      include_timeframes:
        - 5m
      include_corr_pairlist:
        - ATOM/USDT
        - MATIC/USDT
        - ADA/USDT
        - ALGO/USDT
        - APE/USDT
        - ATOM/USDT
        - AVAX/USDT
        - BCH/USDT
        - BTC/USDT
        - DAI/USDT
        - DOGE/USDT
        - DOT/USDT
        - EOS/USDT
        - ETH/USDT
        - LINK/USDT
        - LTC/USDT
        - MANA/USDT
        - MATIC/USDT
        - SHIB/USDT
        - SOL/USDT
        - XMR/USDT
        - XRP/USDT
        - XTZ/USDT
      label_period_candles: 20
      include_shifted_candles: 2
      DI_threshold: 0.9
      weight_factor: 0.9
      principal_component_analysis: false
      use_SVM_to_remove_outliers: true
      indicator_periods_candles:
        - 3
        - 10
        - 20
    data_split_parameters:
      test_size: 0
      random_state: 1
    model_training_parameters:
      n_estimators: 800
      
bot:
  debug: false
  debuglevel: -vvv
  enabled: true
  strategy_name: Anomaly
  pvc_size: 1Gi
  freqaimodel: LightGBMRegressor # ReinforcementLearner # 
# image:
#   base: europe-west1-docker.pkg.dev/vaulted-gift-406223/dersalvador/freqtradeorg/freqtrade@sha256   # europe-west1-docker.pkg.dev/vaulted-gift-406223/dersalvador-dockerhub/freqtradeorg/freqtrade
#   tag: 47467ed88878616adca7d658f14e06285b29cc3457962fe127d16e0d700716f5  # df15774d4422dde9ad25e779402cb92631046a76cb24ea4f37e45036ffc01007 # 2023.12_freqaitorch as base image
