configcreds:
  max_open_trades: -1
  entry_pricing: 
    price_side: same
    use_order_book: true
    order_book_top: 1
    price_last_balance: 0.0
    check_depth_of_market:
      enabled: false
      bids_to_ask_delta: 1
  exit_pricing:
    price_side: same
    use_order_book: true
    order_book_top: 1
  order_types:  
    entry: limit
    exit: limit
    stoploss: market
    stoploss_on_exchange: false
  trading_mode: futures
  margin_mode: isolated
  dataformat_ohlcv: feather
  dataformat_trades: feather  
  download_trades: true
  bot_name: freqtrading-binance-futures
  dry_run: false
  dry_run_wallet: 4000
  stake_amount: 100
  position_adjustment_enable: true
  exchange:
    name: binance
    key: ZJ8HMz2H5G1HMqcZh5yIJmoCVcWrYZLp9ZUqMhhSlb6mdJnzjUkNrdN8rJ4Zw7ro
    secret: Q37TvH7ORApOdkNl7IYvLhBVjxhcGzGagvH86jrJCHEtTeUsxPZGlPTe8wYpqWfO
  telegram:
    enabled: true
    token: "6271542729:AAFvduNLbNHDhi2_381mqBymKZomA1TAL7I"
    chat_id: "5711830404"
bot:
  debug: false
  debuglevel: -vvv
  enabled: true
  strategy_name: NostalgiaForInfinityX4 #  Strategy005 #  NostalgiaForInfinityNext_ChangeToTower_V5_2 # Strategy005 # Strategy005 #  NostalgiaForInfinityNext_ChangeToTower_V5_2 # NostalgiaForInfinityNext_ChangeToTower_V5_2 # Strategy005
  pvc_size: 1Gi
  freqaimodel: LightGBMRegressor 
