---
nostalgiaforinfinity:
  holdtrades:
    trade_pairs:
      BTC/USDT: 0.3
      ETH/USDT: 0.3
      ADA/USDT: 0.1
      ALGO/USDT: 0.1
      APE/USDT: 0.1
      ATOM/USDT: 0.1
      AVAX/USDT: 0.1
      BCH/USDT: 0.1
      DAI/USDT: 0.1
      DOGE/USDT: 0.1
      DOT/USDT: 0.1
      EOS/USDT: 0.1
      EURT/USDT: 0.1
      LINK/USDT: 0.1
      LTC/USDT: 0.1
      MANA/USDT: 0.1
      MATIC/USDT: 0.1
      SHIB/USDT: 0.1
      SOL/USDT: 0.1
      USDC/USDT: 0.1
      USTC/USDT: 0.1
      XMR/USDT: 0.1
      XRP/USDT: 0.1
      XTZ/USDT: 0.1
config:
  trading_mode: spot
  minimal_roi:
    "0": 0.9
    "40160": 0.09
    "80160": 0  
  timeframe: 5m
  stoploss: -0.99
  trailing_stop: false
  trailing_only_offset_is_reached: false
  trailing_stop_positive: 0.01
  trailing_stop_positive_offset: 0.03
  use_custom_stoploss: false
  has_downtime_protection: false
  # Do you want to use the hold feature? (with hold-trades.json)
  hold_support_enabled: true
  # Run "populate_indicators()" only for new candle.
  process_only_new_candles: true
  # These values can be overridden in the "ask_strategy" section in the config.
  use_exit_signal: true
  ignore_roi_if_entry_signal: true
  # Number of candles the strategy requires before producing valid signals
  # startup_candle_count: 720 # kraken doesnt provide 720 candles for 5m timeframe
  stake_amount_type: quote_currency
  entry_pricing:
    price_side: other
    use_order_book: true
    order_book_top: 1
    price_last_balance: 0
    check_depth_of_market:
      enabled: false
      bids_to_ask_delta: 1
  exit_pricing:
    price_side: other
    use_order_book: true
    order_book_top: 1
  dataformat_ohlcv: feather
  dataformat_trades: feather
  download_trades: true
  dry_run: false
  dry_run_wallet: 4000
  stake_amount: unlimited
  position_adjustment_enable: false
  include_timeframes: [1m, 5m, 15m, 30m, 1h, 4h, 1d]
  max_open_trades: 5
  amend_last_stake_amount: true
  stake_currency: USDT
  tradable_balance_ratio: 0.99
  # fiat_display_currency: USD
  db_url: "sqlite:///user_data/tradesv3.sqlite"
  cancel_open_orders_on_exit: false
  exit_profit_only: true
  margin_mode: ""
  unfilledtimeout:
    entry: 10
    exit: 30
    exit_timeout_count: 0
    unit: minutes
  order_types:
    entry: "market"
    force_entry: "market"
    force_exit: "market"
    exit: limit
    stoploss: "market"
    stoploss_on_exchange: false
  exchange:
    ccxt_config:
      enableRateLimit: true
      rateLimit: 1200
      options:
        defaultType: spot
        leverage: 10
    ccxt_async_config:
      enableRateLimit: true
      rateLimit: 1200
      options:
        defaultType: spot
        leverage: 10
    pair_whitelist_disabled: []
    pair_blacklist_disabled: []
    pair_blacklist: [
              # Leverage tokens
              ".*(3L|3S|5L|5S|UP|DOWN)/.*",
              # Fiat
              "(AUD|BRZ|CAD|CHF|EUR|GBP|HKD|IDRT|JPY|NGN|RUB|SGD|TRY|UAH|USD|ZAR)/.*",
              # Stable tokens
              "(BUSD|CUSD|CUSDT|DAI|PAXG|SUSD|TUSD|USDC|USDN|USDP|USDT|VAI|UST|USDD|USDJ|USTC|AUSD|OUSD|PYUSD)/.*",
              # FAN Tokens
              "(ACM|AFA|ALA|ALL|ALPINE|APL|ASR|ATM|BAR|CAI|CITY|FOR|GAL|GOZ|IBFK|JUV|LEG|LOCK-1|NAVI|NMR|NOV|PFL|PORTO|PSG|ROUSH|STV|TH|TRA|UCH|UFC|YBO)/.*",
              # Other Coins
              "(1EARTH|ILA|MEM|AMPL|BOBA|CWAR|OMG|XYM|POLX|CARR|SKEY|KLV|KRL|KOK|DMTR|CHMB|CPOOL|MLS|RBS|SRBS|SYLO|VR|KARA|LUNA|SRBP|PSL|AI|QKC|EPK|BAX|UQC|ZBC|PLATO|ACA|XCN|MC|FTT|SRM|PRMX|SWP|XWG|PIAS|KICKS|TIME|BNX|WEMIX|HI.*|ALBT|ANC|CIX100|GLCH|MIR|XTAG|CELT|TEM|ZKT|MVP|ADB|AXPR|H2O|FT|BNC|BNX|STG|RLY|HNT|MARS4|DRGN|WXT|ROSN|KYL|FRR|STARLY|RBP|UNB|ARNM|NGC|CARE|REAP|TEM|EDG|GOM2|GRIN|INDI|LOVE|NGM|SHFT|ASTRA|PEPE|SOLVE|SUKU|ECOX|JASMY|GFT|PNT|AMB|BASIC|LMWR|VEGA|COCOS|PKF|SHX|DAPPT|BOB|ID|ZPAY|XHV|PCX|MODEFI|PEPE2|TRIBE|RFUEL|SIN|UBX|NOM|QUARTZ|XED|DG|SLCL|PLGR|OPCT|GMB|COV|TAUM|HAWK|LAVAX|CPC|AOA|EFX|FKX|JAR|NRG|REV|OXEN|UBX|CIX100|LOC|IXS|FORESTPLUS|BNS|MNET|EQZ|LACE|VID|H3RO3S|2CRZ|RACEFI|WOM|DERO|MLN|MEME|TOKEN)/.*"
          ]

  pairlists:
    - method: RemotePairList
      number_assets: 50
      pairlist_url: http://filekeys.com/remotepairlist-white-spot.json # https://remotepairlist.com?q=175979476d5fc223
      processing_mode: filter
      mode: whitelist
      sort_key: quoteVolume
      refresh_period: 900
      keep_pairlist_on_failure: true
      read_timeout: 60  
    # - method: StaticPairList
    #   processing_mode: append
    #   mode: blacklist

    # - method: RemotePairList
    #   number_assets: 50
    #   pairlist_url: https://remotepairlist.com?q=ac822c0252729ed2
    #   processing_mode: filter
    #   mode: blacklist
    #   sort_key: quoteVolume
    #   refresh_period: 900
    #   keep_pairlist_on_failure: true
    #   read_timeout: 60
    # - method: AgeFilter
    #   min_days_listed: 15
    # - method: PriceFilter
    #   low_price_ratio: 0.003
    # - method: SpreadFilter
    #   max_spread_ratio: 0.008
    # - method: RangeStabilityFilter
    #   lookback_days: 30
    #   min_rate_of_change: 0.01
    #   refresh_period: 900
    # - method: ShuffleFilter
  freqai:
    enabled: false
    fit_live_predictions_candles: 300
    purge_old_models: true
    train_period_days: 30
    identifier: unique-id
    live_retrain_hours: 1
    feature_parameters:
      include_timeframes:
        - 5m
      include_corr_pairlist:
        - ATOM/USDT
        - MATIC/USDT
        - ADA/USDT
        - ALGO/USDT
        - APE/USDT
        - ATOM/USDT
        - AVAX/USDT
        - BCH/USDT
        - BTC/USDT
        - DAI/USDT
        - DOGE/USDT
        - DOT/USDT
        - EOS/USDT
        - ETH/USDT
        - EURT/USDT
        - LINK/USDT
        - LTC/USDT
        - MANA/USDT
        - MATIC/USDT
        - SHIB/USDT
        - SOL/USDT
        - XMR/USDT
        - XRP/USDT
        - XTZ/USDT
      label_period_candles: 20
      include_shifted_candles: 2
      DI_threshold: 0.9
      weight_factor: 0.9
      principal_component_analysis: false
      use_SVM_to_remove_outliers: true
      indicator_periods_candles:
        - 3
        - 10
        - 20
    data_split_parameters:
      test_size: 0
      random_state: 1
    model_training_parameters:
      n_estimators: 800      
  telegram:
    keyboard:
      - - /forcelong
        - /balance
        - /profit
        - /reload_config
        - /stopentry
      - - /status table
        - /performance
        - /mix_tags
        - /start
        - /stop
      - - /show_config
        - /whitelist
        - /logs
        - /trades
        - /forceexit
  api_server:
    enabled: true
    listen_ip_address: 0.0.0.0
    listen_port: 8084
    verbosity: error
    enable_openapi: true
    jwt_secret_key: |
      235573d45bb26d0cbf1986893b12d4aaf0cf4934f3566d9459d818ec7fbb851b
    ws_token: acnQI1n44GG9lJ51fLKqWQvVJF5k5q7xsw
    CORS_origins:
      - "http://127.0.0.1:8084"
      - "http://localhost:8084"
      - "http://0.0.0.0:8084"
    username: freqtrade
    password: "&&Liz270117!!"
  initial_state: stopped
  force_entry_enable: true
  internals:
    process_throttle_secs: 5
bot:
  webserver_deployment: false   
  pvc_size: 4Gi
  debug: false
  debuglevel: -vvv
  enabled: true  
image:
  base: europe-west1-docker.pkg.dev/vaulted-gift-406223/dersalvador/freqtradeorg/freqtrade@sha256 # europe-west1-docker.pkg.dev/vaulted-gift-406223/dersalvador-dockerhub/freqtradeorg/freqtrade
  tag: e7031abd16e0eef1ea8d9fd49e5ba932c0f4802ff047b0db28964412cb97df6f # d9008638d57857a8ca0c0dc7f3ba60c98b04655a3ceeb156520a0eb521a0d663 # df15774d4422dde9ad25e779402cb92631046a76cb24ea4f37e45036ffc01007 # 5d6c0ba5b69c89978a3353831164745e98e9fef0e134a29fa8108ad65c1dcfcf # 2023.11_freqaitorch
backtesting:
  enabled: false
  download_data: false
  timerange:
  timeframes: 1h
  strategy_list: Strategy005
  fee:
  pvc_size: 4Gi
  results:
    enable_export: false
    reader_enabled: false
    pvc_size: 4Gi
ingress:
  enabled: true
create_config_configmap: true
create_strategies_configmap: true
strategies: []
