configcreds:
  bot_name: freqtrade-kraken-stieves
  dry_run: false
  dry_run_wallet: 100000
  download_trades: false
  position_adjustment_enable: true
  stake_amount: unlimited
  entry_pricing:
    price_side: same
    use_order_book: true
    order_book_top: 1
    price_last_balance: 0
    check_depth_of_market:
      enabled: false
      bids_to_ask_delta: 1
  exit_pricing:
    price_side: same
    use_order_book: true
    order_book_top: 1
  order_types: 
    entry: "limit"
    force_entry: "market"
    force_exit: "market"
    exit: limit
    stoploss: "market"
    stoploss_on_exchange: false  
  exchange:
    name: kraken
    key: iYMnr561Jd2W/5mO5vGh0dRkxVuRIIFASiyMg438+JxOo+3x4E0hRsRg
    secret: >-
        7WUb1oOKiy13s45HBDO9s+LMzjw6SXpsLAYuKC5biErZ83Wjt+fTY/QL7s2R6qG/5NCLr2EyxGJE1tqVMshJgQ==
  telegram:
    enabled: true
    token: "6896507427:AAH1t5Z5Nfww5Izoms6tHo5hq6PdP6d0q58"
    chat_id: "743804896"
    # token: "6896507427:AAH1t5Z5Nfww5Izoms6tHo5hq6PdP6d0q58"
    # chat_id: "743804896"
bot:  
  enabled: true
  strategy_name: turbov8
  pvc_size: 1Gi
  freqaimodel: LightGBMRegressor #  ReinforcementLearner
  # freqaimodel: ReinforcementLearner # LightGBMRegressor

 # Stefan token: "6896507427:AAH1t5Z5Nfww5Izoms6tHo5hq6PdP6d0q58"
 # Stefan chat_id: "743804896"
