---
kubernetes:
  nodePort: 32331
configcreds:
  available_capital: 212 
  leverage: 4
  max_open_trades: 9
  trailing_stop: false
  trailing_stop_positive: 0.99
  trailing_stop_positive_offset: 0.2
  trailing_only_offset_is_reached: true  
  trading_mode: futures
  margin_mode: isolated
  bot_name: freqtrading-binance-futures-larissa
  freqai:
    enabled: false
    fit_live_predictions_candles: 300
    purge_old_models: true
    train_period_days: 30
    identifier: unique-id
    live_retrain_hours: 1
    feature_parameters:
      include_timeframes:
        - 15m
      include_corr_pairlist:
        - ATOM/USDT
        - MATIC/USDT
        - ADA/USDT
        - ALGO/USDT
        - APE/USDT
        - ATOM/USDT
        - AVAX/USDT
        - BCH/USDT
        - BTC/USDT
        - DAI/USDT
        - DOGE/USDT
        - DOT/USDT
        - EOS/USDT
        - ETH/USDT
        - LINK/USDT
        - LTC/USDT
        - MANA/USDT
        - MATIC/USDT
        - SHIB/USDT
        - SOL/USDT
        - XMR/USDT
        - XRP/USDT
        - XTZ/USDT
      label_period_candles: 20
      include_shifted_candles: 2
      DI_threshold: 0.9
      weight_factor: 0.9
      principal_component_analysis: false
      use_SVM_to_remove_outliers: true
      indicator_periods_candles:
        - 3
        - 10
        - 20
    data_split_parameters:
      test_size: 0
      random_state: 1
    model_training_parameters:
      n_estimators: 800  
  exchange:
    ccxt_config:
      enableRateLimit: true
      rateLimit: 1200
      options:
        defaultType: future
        leverage: 100
    ccxt_async_config:
      enableRateLimit: true
      rateLimit: 1200
      options:
        defaultType: future
        leverage: 100
    name: binance
    key: Zp2MxtUwPPofPylEiAhO8sR9DJlWycMVnfvnZTSdalSmkx8g9BNxE7j2g0YJC0OY # eU4J1XrpnGLKNpxjSE16AIPnxkjOVCp6twsieeOOng9g97zvICIYbChITn0nCwe7
    secret: JRJfHc1o3tdKXy384M1PUFPGtpRFEmhVTd0DNgOmzj17Oqrq74kyM5Ltj6iSQpVX
  pairlists:
    - method: RemotePairList
      number_assets: 50
      pairlist_url: https://remotepairlist.com?q=6ed672791d1040c0 #  https://remotepairlist.com?q=5f29a5242f9965b4 #  http://filekeys.com/remotepairlist-white-futures.json # https://remotepairlist.com?q=5f29a5242f9965b4
      mode: whitelist
      processing_mode: append
      refresh_period: 900
      keep_pairlist_on_failure: true
      read_timeout: 120
    - method: RemotePairList
      number_assets: 50
      pairlist_url: http://filekeys.com/remotepairlist-white-futures-static.json  # http://filekeys.com/remotepairlist-white-futures.json   # https://remotepairlist.com?q=6ed672791d1040c0
      mode: whitelist
      processing_mode: append
      refresh_period: 900
      keep_pairlist_on_failure: true
      read_timeout: 120           
    # - method: RemotePairList
    #   number_assets: 50
    #   mode: blacklist
    #   pairlist_url: https://remotepairlist.com?q=26cea181734d3856
    #   processing_mode: append
    #   refresh_period: 900
    #   keep_pairlist_on_failure: true
    #   read_timeout: 120
    # - method: AgeFilter
    #   min_days_listed: 30
    # - method: PriceFilter
    #   low_price_ratio: 0.01
    # - method: SpreadFilter
    #   max_spread_ratio: 0.1
    # - method: RangeStabilityFilter
    #   lookback_days: 3
    #   min_rate_of_change: 0.1
    #   refresh_period: 1800
    # - method: ShuffleFilter
  telegram:
    enabled: true
    token: "6905337607:AAH6DrgfnKmG8NV9m0RTZuf2wLcJ7MveMkQ"
    chat_id: "6560340088"
bot:
  debug: false
  debuglevel: -vvv
  enabled: true
  # DWT_LongShort only long futures
  strategy_name: DWT_LongShort
  pvc_size: 1Gi
  freqaimodel: LightGBMRegressor
# image:
#   base: europe-west1-docker.pkg.dev/vaulted-gift-406223/dersalvador/freqtradeorg/freqtrade@sha256   # europe-west1-docker.pkg.dev/vaulted-gift-406223/dersalvador-dockerhub/freqtradeorg/freqtrade
#   tag: 47467ed88878616adca7d658f14e06285b29cc3457962fe127d16e0d700716f5  # df15774d4422dde9ad25e779402cb92631046a76cb24ea4f37e45036ffc01007 # 2023.12_freqaitorch as base image