configcreds:
  stake_amount: 100
  exchange:
    name: kraken
    key: iYMnr561Jd2W/5mO5vGh0dRkxVuRIIFASiyMg438+JxOo+3x4E0hRsRg
    secret: >-
        7WUb1oOKiy13s45HBDO9s+LMzjw6SXpsLAYuKC5biErZ83Wjt+fTY/QL7s2R6qG/5NCLr2EyxGJE1tqVMshJgQ==
  telegram:
    enabled: true
    token: "6896507427:AAH1t5Z5Nfww5Izoms6tHo5hq6PdP6d0q58"
    chat_id: "743804896"
    # token: "6896507427:AAH1t5Z5Nfww5Izoms6tHo5hq6PdP6d0q58"
    # chat_id: "743804896"
bot:  
  enabled: true
  strategy_name: Strategy005
  pvc_size: 1Gi
  freqaimodel: LightGBMRegressor #  ReinforcementLearner
  # freqaimodel: ReinforcementLearner # LightGBMRegressor

 # Stefan token: "6896507427:AAH1t5Z5Nfww5Izoms6tHo5hq6PdP6d0q58"
 # Stefan chat_id: "743804896"
