configcreds:
  stake_amount: unlimited
  exchange:
    name: binance
    key: z12MdhIr1GXvEWzA6ZI3N3SBT9lA3L0AaZbdFbBTMiz9dIKpqedNDP8xwt7q1G0f
    secret: kTSbbt3MZ35z9EiOOrFArOVVM9YYubpHOp7VC1RD2UJFru7VO6r9fgUY201PeYrU
  telegram:
    enabled: true
    token: "6769081383:AAEls-xws8eZw4vv-adHpnTWqbnWGliHnSE"
    chat_id: "477936067"

bot:
  debug: false
  debuglevel: -vvv
  enabled: true
  strategy_name: NostalgiaForInfinityNext_ChangeToTower_V5_2 # Strategy005
  pvc_size: 1Gi
  freqaimodel: LightGBMRegressor 
