---
kubernetes:
  nodePort: 32327

configcreds:
  bot_name: freqtrade-kraken-adriana
  timeframe: 5m
  trading_mode: spot
  stake_amount: unlimited
  
  exchange:
    name: kraken
    ccxt_config:
      enableRateLimit: true
      rateLimit: 3000
      options:
        defaultType: spot
        leverage: 10
    ccxt_async_config:
      enableRateLimit: true
      rateLimit: 3000
      options:
        defaultType: spot
        leverage: 10  
    key: +H4NKdY1EIWMVwq4s+qOymZATOYoQPvND+wCMzo+jasiN+zScLEVPODo
    secret: jOrx0aLMbRzOjAoagVx0nU1fW2qzTvvT+2bZQNIehqjKfieATglkZ+o92QJm9AuCCdmH4k3owys+nWHKlCEJmw==
  telegram:
    enabled: true
    token: "6687835448:AAE4LHQGt4wLoJFstZ4H0eoMhhg4u3k7UJo"
    chat_id: "6274423445"
    # Stefan token: "6896507427:AAH1t5Z5Nfww5Izoms6tHo5hq6PdP6d0q58"
    # Stefan chat_id: "743804896"
    # Adriana token: "6687835448:AAE4LHQGt4wLoJFstZ4H0eoMhhg4u3k7UJo"
    # Adriana chat_id: "6274423445"
bot:
  enabled: true
  strategy_name: Anomaly
  pvc_size: 1Gi
  freqaimodel: LightGBMRegressor

image:
  base: europe-west1-docker.pkg.dev/vaulted-gift-406223/dersalvador/freqtradeorg/freqtrade@sha256 # europe-west1-docker.pkg.dev/vaulted-gift-406223/dersalvador-dockerhub/freqtradeorg/freqtrade
  tag: 4e74f75c56cb3dd6b3cd58b2ffb37b0d297fd5f521f56f4ebee292e69b40b16d # 2024.1_freqaitorch_ds_2
  

