---
kubernetes:
  nodePort: 32328
configcreds:
  bot_name: freqtrade-kraken-hellen
  exchange:
    name: kraken
    key: X6beWu84orWoCoXmAD0jVRcVBRAJ3VhlhZpu7TGKSiGifT6UWCHH3Jf8
    secret: YhuqDH/BGwTevnUIBr8o9Kaw6fnjqNP3NZ/wF9nX3Dk4Efz1Uc2qyzT2RALy2rMJjdsjgOl7c4kC654NatBYuA==
  telegram:
    enabled: true
    token: "6471453483:AAEM8wy0zTfCCgUc9Cj3DmMmhbaj9S_MR8s"
    chat_id: "6493643145"
bot:
  enabled: true
  strategy_name: Anomaly
  freqaimodel: LightGBMRegressor
# image:
#   base: europe-west1-docker.pkg.dev/vaulted-gift-406223/dersalvador/freqtradeorg/freqtrade@sha256   # europe-west1-docker.pkg.dev/vaulted-gift-406223/dersalvador-dockerhub/freqtradeorg/freqtrade
#   tag: 47467ed88878616adca7d658f14e06285b29cc3457962fe127d16e0d700716f5  # df15774d4422dde9ad25e779402cb92631046a76cb24ea4f37e45036ffc01007 # 2023.12_freqaitorch as base image