---
kubernetes:
  nodePort: 32323
configcreds:
  stake_amount: 50
  bot_name: freqtrading-binance-hassan
  exchange:
    name: binance
    key: SQVj4WE2YfDgq6kMbOdobyx8OmWGRt4l1aV9DsWGaDMoRKdIRLaa4wu82PUMWhVn
    secret: rGreExUqQL6QMWmAaiWLuAehxUdoShSVHeWbJAHPApktT3nWE6UMBnmz0EDv9zD0
  telegram:
    enabled: true
    token: "6064146874:AAHSR_x0WljvorWkAZztXpTXPa9QTPqQRfU"
    chat_id: "5510878923"
bot:
  debug: false
  debuglevel: -vvv
  enabled: true
  strategy_name: NNTC
  pvc_size: 1Gi
  freqaimodel: LightGBMRegressor

# image:
#   base: europe-west1-docker.pkg.dev/vaulted-gift-406223/dersalvador/freqtradeorg/freqtrade@sha256   # europe-west1-docker.pkg.dev/vaulted-gift-406223/dersalvador-dockerhub/freqtradeorg/freqtrade
#   tag: d42b9362d2133d29f2b3e9ab239d5c21811fbb39d86463e36b2080c90a652436 # df15774d4422dde9ad25e779402cb92631046a76cb24ea4f37e45036ffc01007 # 2023.12_freqaitorch as base image

   

