---
kubernetes:
  nodePort: 32324
configcreds:
  available_capital: 25 
  bot_name: freqtrading-binance-juliano
  exchange:
    name: binance
    key: RCB5nWqiZJa0DnYRjuPbijmuacCY8cBkoVqshEv77O23yWEYvKhWlkVfcUdJVw5T
    secret: MzvSLeBLWUQEqivtnQLasBY1lw8f1Sp4RJ8oXWq4zpKM0bL6PVZ2ZaOR70Y8UPPT
  telegram:
    enabled: false
    token: "6766441579:AAFAKnwwb4oz0AvTO8buY-DWi-1i5pZ3yPs"
    chat_id: "1649376180"
bot:
  debug: false
  debuglevel: -vvv
  enabled: true
  strategy_name: Anomaly
  pvc_size: 1Gi
  freqaimodel: LightGBMRegressor
# image:
#   base: europe-west1-docker.pkg.dev/vaulted-gift-406223/dersalvador/freqtradeorg/freqtrade@sha256   # europe-west1-docker.pkg.dev/vaulted-gift-406223/dersalvador-dockerhub/freqtradeorg/freqtrade
#   tag: 47467ed88878616adca7d658f14e06285b29cc3457962fe127d16e0d700716f5  # df15774d4422dde9ad25e779402cb92631046a76cb24ea4f37e45036ffc01007 # 2023.12_freqaitorch as base image