kubernetes:
  nodePort: 32330

configcreds:
  download_trades: true
  bot_name: freqtrading-binance-adriana
  dry_run: false
  dry_run_wallet: 4000
  stake_amount: unlimited
  position_adjustment_enable: true
  dry_run: false
  dry_run_wallet: 4000
  stake_amount: unlimited
  position_adjustment_enable: true
  exchange:
    name: binance
    key: LmlPrj6XjI1IeMYYvranGRADAkeWWrcgvHkYPG60mbeSNZGt9kxwu0lfDa8rY47P
    secret: TLo2FRs5P7IDqvVI2UTk3fPgKc6W0I3nRWq9F43rX2TfOqQulZOtp4VJBHqWUH62
  telegram:
    enabled: false
    token: "6271542729:AAFvduNLbNHDhi2_381mqBymKZomA1TAL7I"
    chat_id: "5711830404"

bot:
  debug: false
  debuglevel: -vvv
  enabled: true
  strategy_name: Strategy005
  pvc_size: 1Gi
  freqaimodel: LightGBMRegressor 
