---
kubernetes:
  nodeNameBackTestingResultsReader: dynamicValues1
  copyContainer: true
configcreds:
  edge:
    enabled: false
    process_throttle_secs: 3600
    calculate_since_number_of_days: 365
    allowed_risk: 0.00
    stoploss_range_min: -0.01
    stoploss_range_max: -0.1
    stoploss_range_step: -0.01
    minimum_winrate: 0.01
    minimum_expectancy: 0.08
    min_trade_number: 1000
    max_trade_duration_minute: 7440
    remove_pumps: false
    hoursInThePast: "-8760h" # 1 year      
  dersalvador:
    database_path: "/sqlite/tradesv3.sqlite"
    enable_email_logging: true
    hedging:
      hedging_version: 0.2.1
      apikey: b3r35QxZ6z8PKS7vFSoJztdTwI4mQJ1owCBmp08pjKj1FQWhFFxvFZ9yqStfpGwm
      apisecret: tHwYon2naTO6111rCo3c6yv84szDFFsaovNnf9eUY9FYl5Ub07c9IuZ8WTZx4uov
      exit_on_profit: false
      leverage: 10
      stake_amount: 2000
      minimal_hedging_stoploss_length: 5
      hedging_stoploss_length: 10
      # Minimal Threshold 
      minimal_trigger_threshold_adjustment: 2
      trigger_threshold_adjustment: 5
      minimal_hedging_trigger_timeout_seconds: 2
      hedging_trigger_timeout_seconds: 2
      minimal_last_trend_entries: 3
      last_trend_entries: 5
      minimal_hedging_pair_profits_check_array_length: 2
      profits_check_array_length: 5
      minimal_hedging_aggregated_pair_profits_check_array_length: 2
      aggregated_pair_profits_check_array_length: 5
      minimal_hedging_market_profits_check_array_length: 2
      market_profits_check_array_length: 5
      minimal_bullish_threshold_pct: 0.4
      bullish_threshold_pct: 0.7
      minimal_bearish_threshold_pct: 0.4
      bearish_threshold_pct: 0.7
      macd_short_window:  6
      macd_long_window: 26
      macd_signal_window: 9          
      # Timeout     
      minutesLatestTradeDuration: 1
      # Candle Lengths
      # Dataframe Analysis
      market_analysis: true
      pair_aggregated_analysis: true
      # Bullish or Bearish Thresholds
      start_profit_abs_positiv: 0.00001
      start_profit_abs_negative: -0.00001
      candle_divisor: 1
      bullish_partial_threshold_pct: 0.5
      bearish_partial_threshold_pct: 0.5
      bullish_threshold_pct_offset: 0.01
      bearish_threshold_pct_offset: 0.01
      # stoploss_bot_api: "http://freqtrade:'&&Liz270117!!'@freqtrade-clusterip-binance-adriana-futures.binance-adriana-futures.svc.cluster.local:8084/api/v1/forceenter" # binance-adriana-futures
      stoploss_bot_api: "http://freqtrade:'&&Liz270117!!'@freqtrade-clusterip-bot-larissa-do-nothing.bot-larissa-do-nothing.svc.cluster.local:8084/api/v1/forceenter" # binance-adriana-futures
    ds_listdata:
      enable: false
    ds_downloaddata:
      enable: false
      days: 7
      pairs_to_download: XLM/USDT XDC/USDT XRP/USDT IOTA/USDT ALGO/USDT BTC/USDT ETH/USDT USDC/USDT SOL/USDT FDUSD/USDT ENA/USDT PEPE/USDT WIF/USDT XRP/USDT TRB/USDT
    ds_hyperopt:
      enable: false
      enableprotections: true
      hyperlossfunction: ShortTradeDurHyperOptLoss
      hoursInThePast: -48h
    ds_backtesting:
      enable: false
      exportType: signals # {none,trades,signals}
      # one week ago
      hoursInThePast: -48h
