---
kubernetes:
  nodePort: 32326

configcreds:
  available_capital: 1697
  #stake_amount: 50
  bot_name: binance-michael
  trading_mode: spot
  exchange:
    name: binance
    key: b3r35QxZ6z8PKS7vFSoJztdTwI4mQJ1owCBmp08pjKj1FQWhFFxvFZ9yqStfpGwm
    secret: tHwYon2naTO6111rCo3c6yv84szDFFsaovNnf9eUY9FYl5Ub07c9IuZ8WTZx4uov
  telegram:
    enabled: true
    token: "7073717714:AAFWLPwlvE6RLzrrRL0XecU_O9v0IfjJRIo"
    chat_id: "1759706931" # "5711830404"
bot:
  debug: false
  debuglevel: -vvv
  enabled: true
  strategy_name: NNTC
  pvc_size: 1Gi
  freqaimodel: LightGBMRegressor
# image:
#   base: europe-west1-docker.pkg.dev/vaulted-gift-406223/dersalvador/freqtradeorg/freqtrade@sha256   # europe-west1-docker.pkg.dev/vaulted-gift-406223/dersalvador-dockerhub/freqtradeorg/freqtrade
#   tag: 47467ed88878616adca7d658f14e06285b29cc3457962fe127d16e0d700716f5  # df15774d4422dde9ad25e779402cb92631046a76cb24ea4f37e45036ffc01007 # 2023.12_freqaitorch as base image
