---
kubernetes:
  nodePort: 32335
configcreds:
  # listdata:
  #   enable: false
  # downloaddata:
  #   enable: false
  #   days: 7
  #   pairs_to_download: XLM/USDT XDC/USDT XRP/USDT IOTA/USDT ALGO/USDT BTC/USDT ETH/USDT USDC/USDT SOL/USDT FDUSD/USDT ENA/USDT PEPE/USDT WIF/USDT XRP/USDT TRB/USDT
  # hyperopt:
  #   enable: false
  #   enableprotections: true
  #   hyperlossfunction: ShortTradeDurHyperOptLoss
  #   # "ShortTradeDurHyperOptLoss SharpeHyperOptLoss SharpeHyperOptLossDaily 
  #   # SortinoHyperOptLoss SortinoHyperOptLossDaily CalmarHyperOptLoss MaxDrawDownHyperOptLoss 
  #   # MaxDrawDownRelativeHyperOptLoss ProfitDrawDownHyperOptLoss OnlyProfitHyperOptLoss"
  #   hoursInThePast: -48h
  # backtesting:
  #   enable: false
  #   exportType: signals # {none,trades,signals}
  #   # one week ago
  #   hoursInThePast: -48h
  #   # timerage: {{ now | dateModify "-168h" | date "20060102"  }}-{{ now | date "20060102" }}
  #   # One year back
  #   # timerage: {{ now | dateModify "-8766h" | date "20060102"  }}-{{ now | date "20060102" }}
  bot_name: binance-adriana-futures
  dry_run: true
  timeframe: 5m
  # available_capital: 600
  max_open_trades: 60
  stake_amount: 200
  minimal_roi:
    "0": 0.1
  stoploss: -0.001
  leverage: 3
  trading_mode: futures
  margin_mode: isolated
  position_adjustment_enable: false
  exchange:
    name: binance
    key: E1Hep4aT7iRTbsEjC34bQXQt5l779vWHMbRyJG5r3b07KIhgMUzJ9J6y3SGSF2ZN #  xngX47kLt00jdiCkmY7Nj06peqjVnzRN6ZShvc6PBJH6LeRUw0MD23aVkfzQu199 # ZIvg+5kZpbxQFQLsGoQtu5Rj1p8JZx+eE3b5v5uGqhS2ORWX8C1oU1bA
    secret: 1jKDzu9csiFtSpqpe6PetJAmRedge6tIHHjSsH8LeWGKwkt18v173bsM0gZS2gQ1 # lFrW07av9Ed61h1LW0pnin2WUDcVZy9cWp648QBBhhHh5csbkuauPDxW4M1v1wYw # EMPRVS0QkTXSNZBWrwn+mg47db2Y2Mf85lFsjXuTlEnX7tmL0bAkjoPYIRrs6IwdR5VFu38IOJO0BM4QAFiYCg==
  telegram:
    enabled: true
    token: 6632710647:AAF62LDqnrHf83KIIeSAtqsr6mgB6aKeL3Y # 7020581178:AAGN2KOhJ3jCCXL_0p8s77uKo_5YPgICB1Y # "6687835448:AAE4LHQGt4wLoJFstZ4H0eoMhhg4u3k7UJo"
    chat_id: "1759706931" # "6274423445"
bot:
  strategy_name: DoesNothingStrategy
