config:
  timeframe: 1m
  include_timeframes: [ "1m", "3m", "5m", "15m", "30m", "1h", "2h", "4h", "6h", "8h", "12h", "1d", "3d", "1w", "1M" ] 
  max_open_trades: 4
  amend_last_stake_amount: true
  stake_currency: USDT
  stake_amount: unlimited
  tradable_balance_ratio: 0.99
  fiat_display_currency: EUR
  db_url: "sqlite:///user_data/tradesv3.sqlite"
  dry_run: false
  dry_run_wallet: 20
  cancel_open_orders_on_exit: false
  trading_mode: spot
  available_capital: 4000
  amend_last_stake_amount: true
  #last_stake_amount_min_ratio: 0.8
  #exit_profit_only: false
  #exit_profit_offset: 0.05
  margin_mode: ""
  unfilledtimeout:
    entry: 10
    exit: 30
    exit_timeout_count: 0
    unit: minutes
  entry_pricing:
    price_side: other
    use_order_book: true
    order_book_top: 1
    price_last_balance: 0
    check_depth_of_market:
      enabled: false
      bids_to_ask_delta: 1
  exit_pricing:
    price_side: other
    use_order_book: true
    order_book_top: 1
  download_trades: false
  exchange:
    name: binance
    key: HrLllzlPhN2BAAChE7iQdewMvawTuEwLGkWPYU1ZqlnxJ1uN1IdUernLvk6rU5cF
    secret: >-
      HSeKgVJP2XpL7AJWENZ54p2QexsWZq25jT3i8ywHpSLA7zKijo8yoKvFFTweTIYF
    ccxt_config:
      enableRateLimit: true
    ccxt_async_config:
      enableRateLimit: true
      rateLimit: 2500
    # pair_whitelist: [ "BTC/USDT", "ACM/USDT", "ADA/USDT", "AKRO/USDT", "ALGO/USDT", "ALICE/USDT", "ANKR/USDT", "ATOM/USDT", "AVAX/USDT", "BCH/USDT", "DOGE/USDT", "DOT/USDT", "EOS/USDT", "LINK/USDT", "LTC/USDT", "MANA/USDT", "MATIC/USDT", "SHIB/USDT", "SOL/USDT", "USDC/USDT", "XMR/USDT", "XRP/USDT", "XTZ/USDT", "ETH/USDT", "ACA/USDT", "APE/USDT", "AMB/USDT", "USTC/USDT", "ARB/USDT", "AERGO/USDT" ]
    pair_whitelist_backtesting: [ "BTC/USDT", "USDC/USDT", "ETH/USDT", "DOT/USDT", "XMR/USDT", "LTC/USDT", "XRP/USDT", "ADA/USDT", "DAI/USDT", "SOL/USDT", "LINK/USDT", "EOS/USDT", "DOGE/USDT", "MATIC/USDT", "ATOM/USDT", "BCH/USDT", "SHIB/USDT", "AVAX/USDT", "ALGO/USDT", "APE/USDT", "XTZ/USDT", "MANA/USDT", "USTC/USDT" ]
    pair_blacklist: []
    pair_whitelist: []
  pairlists:
     - method: RemotePairList
       mode: whitelist
       processing_mode: append
       pairlist_url: http://filekeys.com/binance-pairs.json
       number_assets: 30
       refresh_period: 1800
       keep_pairlist_on_failure: true
       read_timeout: 60  
    # - method: PriceFilter
    #   min_price: 100
    # - method: StaticPairList
    #   number_assets: 30
    #   sort_key: quoteVolume
    #   min_value: 0
    #   refresh_period: 1800
    # - method: PriceFilter
    #   min_price: 100
    #- method: StaticPairList
    #  number_assets: 24
    #  sort_key: quoteVolume
    #  min_value: 0
    #  refresh_period: 1800
  telegram:
    enabled: true
    token: "6766441579:AAFAKnwwb4oz0AvTO8buY-DWi-1i5pZ3yPs"
    chat_id: "1649376180"
    keyboard:
      - - /daily
        - /stats
        - /balance
        - /profit
        - /reload_config
        - /stopentry
      - - /status table
        - /performance
        - /mix_tags
        - /start
        - /stop
      - - /show_config
        - /whitelist
        - /logs
        - /trades
  api_server:
    enabled: true
    listen_ip_address: 0.0.0.0
    listen_port: 8084
    verbosity: error
    enable_openapi: false
    jwt_secret_key: 235573d45bb26d0cbf1986893b12d4aaf0cf4934f3566d9459d818ec7fbb851b
    ws_token: acnQI1n44GG9lJ51fLKqWQvVJF5k5q7xsw
    CORS_origins:
      - "http://127.0.0.1:8084"
      - "http://localhost:8084"
      - "http://0.0.0.0:8084"
    username: freqtrade
    password: "&&Liz270117!!"
  freqai:
    rl_config:
      train_cycles: 25
      add_state_info: true
      max_trade_duration_candles: 300
      max_training_drawdown_pct: 0.02
      cpu_count: 8
      model_type: PPO
      policy_type: MlpPolicy
      model_reward_parameters:
        rr: 1
        profit_aim: 0.5
    enabled: true
    purge_old_models: 2
    train_period_days: 15
    backtest_period_days: 7
    live_retrain_hours: 0
    identifier: uniqe-id
    feature_parameters:
      include_timeframes:
        - 5m 
        - 15m 
        - 30m 
        - 1h 
        - 2h 
        - 4h 
        - 6h 
        - 8h 
        - 12h 
        - 1d 
        - 3d 
        - 1w 
        - 1M
      include_corr_pairlist: []
      label_period_candles: 20
      include_shifted_candles: 2
      DI_threshold: 0.9
      weight_factor: 0.9
      principal_component_analysis: false
      use_SVM_to_remove_outliers: true
      indicator_periods_candles:
        - 10
        - 20
      plot_feature_importances: 0
    data_split_parameters:
      test_size: 0.33
      random_state: 1
    model_training_parameters: {}
  bot_name: freqtrade-binance-juliano
  initial_state: running
  force_entry_enable: true
  internals:
    process_throttle_secs: 5
  minimal_roi:
    "0": 0.8
    "10160": 0.5
    "15160": 0.25
    "20160": 0
    #"0": 0.5
    #"40": 0.3

image:
  base: freqtradeorg/freqtrade
  tag: 2023.8_freqairl

backtesting:
  enabled: false
  download_data: false
  timerange:
  timeframes: 5m
  strategy_list: Strategy005 #  SwingHighToSky #  ClucHAnix_BB_RPB_MOD_E0V1E_ROI # TheForce
  fee:
  pvc_size: 1Gi
  results:
    enable_export: true
    reader_enabled: true
    pvc_size: 1Gi

bot:
  debug: true
  debuglevel: -vvv
  enabled: true
  strategy_name: Strategy005 #  SwingHighToSky #  ClucHAnix_BB_RPB_MOD_E0V1E_ROI # TheForce
  pvc_size: 1Gi
  freqaimodel: LightGBMRegressor #  ReinforcementLearner 

ingress:
  enabled: true

create_config_configmap: true
create_strategies_configmap: true

strategies: []
