---
kubernetes:
  nodeNameBackTestingResultsReader: dynamicValues1
  copyContainer: true

configcreds:
  strategy_version: "2025-06-06-11:36"
  imagePullSecrets_github:
    name: github
    username: x1mroepke
    password: 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
    email: michael.santana.mellouk@dersalvador.com

  # exchange:
  #   pair_blacklist:
  #    # - XLM/USDT:USDT
  #    # - ADA/USDT:USDT
  #    # - DOGE/USDT:USDT
  #     - LINK/USDT:USDT
  #    #  - GMX/USDT:USDT
  edge:
    enabled: false
    process_throttle_secs: 3600
    calculate_since_number_of_days: 365
    allowed_risk: 0.00
    stoploss_range_min: -0.01
    stoploss_range_max: -0.1
    stoploss_range_step: -0.01
    minimum_winrate: 0.01
    minimum_expectancy: 0.08
    min_trade_number: 1000
    max_trade_duration_minute: 7440
    remove_pumps: false
    hoursInThePast: "-8760h" # 1 year      
  dersalvador:
    database_path: "/sqlite/tradesv3.sqlite"
    enable_email_logging: false
    hedging:
      hedging_version: v5.0
      apikey: Ie1qiv3hF3gfMGIsyZxdxNDSVSfz8INIWGRKkUwPEejNGRikh2toUVZb1WlH2X2P # b3r35QxZ6z8PKS7vFSoJztdTwI4mQJ1owCBmp08pjKj1FQWhFFxvFZ9yqStfpGwm
      apisecret: 3z4uF8JTXEJLN23IZmQJ9uQuOBc8AdD7ZEwkO5kg5FWm1SsbFMTIIp48usFzhk9r # tHwYon2naTO6111rCo3c6yv84szDFFsaovNnf9eUY9FYl5Ub07c9IuZ8WTZx4uov
      exit_on_profit: false
      bias_determination: restrictive # loose # restrictive
      debug: false
      dataframe_path: /extra_strategies/dataframes/
      binance_timeout: 5
      spot_pair_delay: 5
      thread_delay: 5
      custom_stoploss_max: -0.10
      custom_stoploss_min: -0.08
      spot_aggregated_market_delay: 45 # seconds
      leverage: 5
      stoploss_hedging: false
      minimal_leverage: 5
      stake_amount: 600
      minimal_stoploss_length: 50
      stoploss_length: 70
      lossAbsolutInHedge: -20
      profitAbsolutInHedge: 20
      alternateTrendMinutes: 10
      coinGeckoAPIKey: CG-AgEZRgMf3iLk1S8CwyCKp7N3 # CG-e82vEmuYRAsLxjioT4ezZ6ma #
      status_table_informative_pairs: "BTC/USDT:USDT ETH/USDT:USDT"
      # status_table_informative_pairs: "[ BTC/USDT:USDT ]"
      # Minimal Threshold 
      config_path_serialized: "/extra_strategies/config.json"
      minimal_trigger_threshold_adjustment: 1800
      trigger_threshold_adjustment: 3600
      minimal_trigger_timeout_seconds: 2
      trigger_timeout_seconds: 2
      minimal_last_trend_entries: 3
      last_trend_entries: 5
      minimal_pair_profits_check_array_length: 70
      pair_profits_check_array_length: 100
      minimal_aggregated_pair_profits_check_array_length: 15
      aggregated_pair_profits_check_array_length: 40
      minimal_market_profits_check_array_length: 20
      market_profits_check_array_length: 10
      minimal_bullish_threshold_pct: 0.7
      bullish_threshold_pct: 0.8
      minimal_bearish_threshold_pct: 0.7
      bearish_threshold_pct: 0.8
      macd_short_window: 6
      macd_long_window: 26
      macd_signal_window: 9
      # Timeout     
      minutesLatestTradeDuration: 10 # 60
      hedgeMinutes: 20
      # Candle Lengths
      # Dataframe Analysis
      market_analysis: true
      market_decision_enforced: false
      pair_aggregated_analysis: false
      freqtrade_pair_analysis: false
      # Bullish or Bearish Thresholds
      start_profit_abs_positiv: 1
      start_profit_abs_negative: -1
      candle_divisor: 2
      lostTradeAgeInMinutes: 15
      candle_divisor_freqtrade_candle: 3
      minimal_candle_divisor_freqtrade_candle: 2
      add_new_row_countdown_in_sec: 2
      bullish_partial_threshold_pct: 0.65
      bearish_partial_threshold_pct: 0.65
      bullish_threshold_pct_offset: 0.01
      bearish_threshold_pct_offset: 0.01
      spot_bot_api_forceenter: "http://freqtrade:'&&Liz270117!!'@freqtrade-clusterip-bot-mssm-03.bot-mssm-03.svc.cluster.local:8084/api/v1/forceenter"
      spot_bot_api_status: "http://freqtrade:'&&Liz270117!!'@freqtrade-clusterip-bot-mssm-03.bot-mssm-03.svc.cluster.local:8084/api/v1/status"
      # spot_bot_api_status: "http://freqtrade:'&&Liz270117!!'@freqtrade-clusterip-binance-adriana-futures.svc.cluster.local:8084/api/v1/status"
      hedge_bot_api_final: "http://freqtrade:'&&Liz270117!!'@freqtrade-clusterip-bot-mssm-02.bot-mssm-02.svc.cluster.local:8084/api/v1/forceenter" # binance-adriana-futures
      hedge_bot_api: "http://freqtrade:'&&Liz270117!!'@freqtrade-clusterip-bot-mssm-02.bot-mssm-02.svc.cluster.local:8084/api/v1/forceenter" # binance-adriana-futures
      hedge_bot_api_forceenter: "http://freqtrade:'&&Liz270117!!'@freqtrade-clusterip-bot-mssm-02.bot-mssm-02.svc.cluster.local:8084/api/v1/forceenter"
      stoploss_apikey: E1Hep4aT7iRTbsEjC34bQXQt5l779vWHMbRyJG5r3b07KIhgMUzJ9J6y3SGSF2ZN # adriana
      stoploss_apisecret: 1jKDzu9csiFtSpqpe6PetJAmRedge6tIHHjSsH8LeWGKwkt18v173bsM0gZS2gQ1 # adriana
      hedge_bot_api_trades: "http://freqtrade:'&&Liz270117!!'@freqtrade-clusterip-bot-mssm-02.bot-mssm-02.svc.cluster.local:8084/api/v1/trades" # binance-adriana-futures
      stoploss_bot_api_trades: "http://freqtrade:'&&Liz270117!!'@freqtrade-clusterip-binance-adriana-futures.binance-adriana-futures.svc.cluster.local:8084/api/v1/trades" # binance-adriana-futures
      alternativeHedgingApproach: false
      # stoploss_apikey: b3r35QxZ6z8PKS7vFSoJztdTwI4mQJ1owCBmp08pjKj1FQWhFFxvFZ9yqStfpGwm # michael
      # stoploss_apisecret: tHwYon2naTO6111rCo3c6yv84szDFFsaovNnf9eUY9FYl5Ub07c9IuZ8WTZx4uov # michael
      apikey_observer: UYjkWFpAxfjfOnKjtEXOAj6RT5sirlBjl2fbZkJUYkwyChvxa0cOAtd7A5LrnSET # b3r35QxZ6z8PKS7vFSoJztdTwI4mQJ1owCBmp08pjKj1FQWhFFxvFZ9yqStfpGwm
      apisecret_observer: zTXCHpSQWnzoINkljUamzJx3aYyFr4Js42lCiGe1XJG0Gxb9vq1MsG3Zo5GL42P8 # tHwYon2naTO6111rCo3c6yv84szDFFsaovNnf9eUY9FYl5Ub07c9IuZ8WTZx4uov
      pair_analysis: false
      alternativeHedgingApproach: false
      # stoploss_bot_api: "http://freqtrade:'&&Liz270117!!'@freqtrade-clusterip-binance-adriana-futures.binance-adriana-futures.svc.cluster.local:8084/api/v1/forceenter" # binance-adriana-futures
      # stoploss_bot_api: "http://freqtrade:'&&Liz270117!!'@freqtrade-clusterip-binance-adriana-futures.binance-adriana-futures.svc.cluster.local:8084/api/v1/forceenter" # binance-adriana-futures
      stoploss_bot_api: "http://freqtrade:'&&Liz270117!!'@freqtrade-clusterip-binance-adriana-futures.binance-adriana-futures.svc.cluster.local:8084/api/v1/forceenter" # binance-adriana-futures
      # spot_bot_api_status: "http://freqtrade:'&&Liz270117!!'@freqtrade-clusterip-binance-adriana-futures.binance-adriana-futures.svc.cluster.local:8084/api/v1/status"
      # spot_bot_api_status: "http://freqtrade:'&&Liz270117!!'@freqtrade-clusterip-bot-mssm-01.bot-mssm-01.svc.cluster.local:8084/api/v1/status"
      # spot_bot_api_status: "http://freqtrade:'&&Liz270117!!'@freqtrade-clusterip-bot-mssm-05.bot-mssm-05.svc.cluster.local:8084/api/v1/status"
      spot_bot_api_whitelist: "http://freqtrade:'&&Liz270117!!'@freqtrade-clusterip-bot-mssm-01.bot-mssm-01.svc.cluster.local:8084/api/v1/whitelist"
    ds_listdata:
      enable: false
    ds_downloaddata:
      enable: false
      days: 7
      pairs_to_download: XLM/USDT XDC/USDT XRP/USDT IOTA/USDT ALGO/USDT BTC/USDT ETH/USDT USDC/USDT SOL/USDT FDUSD/USDT ENA/USDT PEPE/USDT WIF/USDT XRP/USDT TRB/USDT
    ds_hyperopt:
      enable: false
      enableprotections: true
      hyperlossfunction: ShortTradeDurHyperOptLoss
      hoursInThePast: -48h
    ds_backtesting:
      enable: false
      exportType: signals # {none,trades,signals}
      # one week ago
      hoursInThePast: -48h
