configcreds:
  stake_amount: unlimited
  exchange:
    name: binance
    key: LmlPrj6XjI1IeMYYvranGRADAkeWWrcgvHkYPG60mbeSNZGt9kxwu0lfDa8rY47P
    secret: >-
      TLo2FRs5P7IDqvVI2UTk3fPgKc6W0I3nRWq9F43rX2TfOqQulZOtp4VJBHqWUH62
  telegram:
    enabled: false
    token: "6271542729:AAFvduNLbNHDhi2_381mqBymKZomA1TAL7I"
    chat_id: "5711830404"