configcreds:
  download_trades: true
  bot_name: freqtrading-binance-juliano
  dry_run: false
  dry_run_wallet: 4000
  stake_amount: unlimited
  position_adjustment_enable: true
  exchange:
    name: binance
    key: HrLllzlPhN2BAAChE7iQdewMvawTuEwLGkWPYU1ZqlnxJ1uN1IdUernLvk6rU5cF
    secret: >-
      HSeKgVJP2XpL7AJWENZ54p2QexsWZq25jT3i8ywHpSLA7zKijo8yoKvFFTweTIYF

  telegram:
    enabled: true
    token: "6766441579:AAFAKnwwb4oz0AvTO8buY-DWi-1i5pZ3yPs"
    chat_id: "1649376180"
 
bot:
  debug: false
  debuglevel: -vvv
  enabled: true
  strategy_name: NostalgiaForInfinityX4 # Strategy005
  pvc_size: 1Gi
  freqaimodel: LightGBMRegressor 
