---
kubernetes:
  nodePort: 32338

configcreds:
  trading_mode: futures
  margin_mode: isolated  
  dry_run: true
  dry_run_wallet: 7000000  
  available_capital: 7000000
  #stake_amount: 50
  bot_name: freqtrading-binance-michael-futures-dry2
  exchange:
    name: binance
    key: ""
    secret: ""
  telegram:
    enabled: false
    token: "6271542729:AAFvduNLbNHDhi2_381mqBymKZomA1TAL7I"
    chat_id: "5711830404"
  freqai:
    rl_config:
      train_cycles: 25
      add_state_info: true
      max_trade_duration_candles: 300
      max_training_drawdown_pct: 0.02
      cpu_count: 8
      model_type: PPO
      policy_type: MlpPolicy
      model_reward_parameters:
        rr: 1
        profit_aim: 0.5
    enabled: true
    fit_live_predictions_candles: 300
    purge_old_models: true # 2
    train_period_days: 30
    identifier: unique-id
    backtest_period_days: 7
    live_retrain_hours: 0
    feature_parameters:
      include_timeframes:
        - 15m
        - 1h
      include_corr_pairlist:
        - ATOM/USDT
        - MATIC/USDT
        - ADA/USDT
        - ALGO/USDT
        - APE/USDT
        - ATOM/USDT
        - AVAX/USDT
        - BCH/USDT
        - BTC/USDT
        - DAI/USDT
        - DOGE/USDT
        - DOT/USDT
        - EOS/USDT
        - ETH/USDT
        - LINK/USDT
        - LTC/USDT
        - MANA/USDT
        - MATIC/USDT
        - SHIB/USDT
        - SOL/USDT
        - XMR/USDT
        - XRP/USDT
        - XTZ/USDT
        - BTC/USDT:USDT
        - ETH/USDT:USDT
      label_period_candles: 20
      include_shifted_candles: 2
      DI_threshold: 0.9
      weight_factor: 0.9
      principal_component_analysis: false
      use_SVM_to_remove_outliers: true
      indicator_periods_candles:
        - 3
        - 10
        - 20
      plot_feature_importances: 0
    data_split_parameters:
      test_size: 0
      random_state: 1
    model_training_parameters:
      n_estimators: 800

bot:
  debug: false
  debuglevel: -vvv
  enabled: true
  strategy_name: AdxSmasS_v7
  pvc_size: 3Gi
  freqaimodel: ReinforcementLearner # LightGBMRegressor
# image:
#   base: europe-west1-docker.pkg.dev/vaulted-gift-406223/dersalvador/freqtradeorg/freqtrade@sha256   # europe-west1-docker.pkg.dev/vaulted-gift-406223/dersalvador-dockerhub/freqtradeorg/freqtrade
#   tag: 47467ed88878616adca7d658f14e06285b29cc3457962fe127d16e0d700716f5  # df15774d4422dde9ad25e779402cb92631046a76cb24ea4f37e45036ffc01007 # 2023.12_freqaitorch as base image
