{{- if .Values.bot.webserver_deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freqtrade-webserver-{{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: freqtrade-webserver-{{ .Release.Namespace }}
  template:
    metadata:
      labels:
        app: freqtrade-webserver-{{ .Release.Namespace }}
    spec:
      initContainers:
      - name: take-sqlite-dir-ownership
        image: {{ .Values.image.base }}:{{ .Values.image.tag }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        command:
        - bash
        - -c
        - |
          echo chown -R ftuser:ftuser /sqlite 
          echo chown -R ftuser:ftuser /freqtrade
          echo chown -R ftuser:ftuser /extra_strategies
          echo chmod -R 777 /extra_strategies
          chown -R ftuser:ftuser /sqlite 
          chown -R ftuser:ftuser /freqtrade
          chown -R ftuser:ftuser /extra_strategies
          chmod -R 777 /extra_strategies
          find /sqlite           
        volumeMounts:
        # - name: extra-strategies
        #   mountPath: /extra_strategies
        #   readOnly: false           
        - mountPath: /sqlite
          name: sqlite    
      # nodeName: {{ .Values.kubernetes.nodeNameBackTestingResultsReader }} # pool-dersalvador-y5w2t # pool-dersalvador-ylyw0
      containers:
      - name: freqtrade-webserver-{{ .Release.Namespace }}
        image: {{ .Values.image.base }}:{{ .Values.image.tag }}
        command:
        - freqtrade
        args:
        - webserver
{{- if .Values.bot.debug }}
        - {{ .Values.bot.debuglevel }}
{{- end }}
        - --config
        - /freqtrade/config/config-{{ .Release.Namespace }}.json
        - --config
        - /freqtrade/configcreds/configcreds-{{ .Release.Namespace }}.json
        - --log-file 
        - /tmp/freqtrade-webserver.log
        - --datadir
        - /freqtrade/user_data/data
        - --userdir
        - /freqtrade/user_data 
        volumeMounts:
        # - name: extra-strategies
        #   mountPath: /extra_strategies
        #   readOnly: false      
        - name: configcreds
          mountPath: /freqtrade/configcreds
        - name: config
          mountPath: /freqtrade/config
        - name: sqlite
          mountPath: /sqlite
        ports:
        - name: api
          containerPort: {{ .Values.config.api_server.listen_port }}
      imagePullSecrets:
      - name: deploy-key-gcr
      volumes:
      # - name: extra-strategies
      #   persistentVolumeClaim:
      #     claimName: freqtrade-extra-strategies        
      - name: configcreds
        configMap:
          name: freqtrade-config-creds-{{ .Release.Namespace }}
      - name: config
        configMap:
          name: freqtrade-config-{{ .Release.Namespace }}
      - name: sqlite
        persistentVolumeClaim:
          claimName: freqtrade-sqlite
---
{{- end }}
