{{- if .Values.bot.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freqtrade-{{ .Release.Namespace }}
  labels:
    app: freqtrade
    env: production   # Adding a label named env with value production
spec:
  selector:
    matchLabels:
      app: freqtrade-{{ .Release.Namespace }}
  template:
    metadata:
      labels:
        app: freqtrade-{{ .Release.Namespace }}
        reason: trading
    spec:
      initContainers:
      - name: take-sqlite-dir-ownership
        image: {{ .Values.image.base }}:{{ .Values.image.tag }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        command:
        - bash
        - -c
        - |
          echo chown -R ftuser:ftuser /tmp 
          echo chown -R ftuser:ftuser /sqlite 
          echo chown -R ftuser:ftuser /freqtrade
          echo chown -R ftuser:ftuser /extra_strategies
          # echo chown -R ftuser:ftuser /extra_strategies
          # echo chmod -R 777 /extra_strategies
          mkdir -p /extra_strategies/logs 
          chown -R ftuser:ftuser /sqlite 
          chown -R ftuser:ftuser /freqtrade
          # chown -R ftuser:ftuser /home/ftuser
          chown -R ftuser:ftuser /extra_strategies
          chmod -R 777 /extra_strategies
          # chmod -R 777 /home/ftuser
          chmod -R 777 /tmp
          find /tmp
          find /sqlite
          find /extra_strategies/logs 
        volumeMounts:
        - name: tmp
          mountPath: /tmp
          readOnly: false            
        - name: extra-strategies
          mountPath: /extra_strategies
          readOnly: false
        - name: user-data-strategies
          mountPath: /freqtrade/user_data/strategies
          readOnly: false
        - mountPath: /sqlite
          name: sqlite

      # - name: liststrategies
      #   image: {{ .Values.image.base }}:{{ .Values.image.tag }}
      #   command:
      #   - bash
      #   - -c
      #   - |
      #      echo pip install python-binance binance_spot binance-connector pywavelets ta ta-lib ta_lib TA-Lib TA_lib multiprocess mailtrap
      #      pip install --user python-binance binance_spot binance-connector pywavelets ta ta-lib ta_lib TA-Lib TA_lib multiprocess mailtrap
      #      . /home/ftuser/.venv/bin/activate
      #      echo mkdir -p "/freqtrade/user_data/strategies"
      #      mkdir -p "/freqtrade/user_data/strategies"
      #      echo cp -R /extra_strategies /freqtrade/user_data/strategies
      #      cp -R /extra_strategies /freqtrade/user_data/strategies
      #      echo ""
      #      echo "Starting Freqtrade list-strategies"
      #      echo ""
      #      # pip install  python-binance binance_spot binance-connector pywavelets ta ta-lib ta_lib TA-Lib TA_lib multiprocess mailtrap
      #      pip install --user python-binance binance_spot binance-connector pywavelets ta ta-lib ta_lib TA-Lib TA_lib multiprocess mailtrap
      #      # freqtrade list-strategies --recursive-strategy-search --strategy-path /extra_strategies --config /freqtrade/config/config-{{ .Release.Namespace }}.json --config /freqtrade/configcreds/configcreds-{{ .Release.Namespace }}.json -d  /extra_strategies/data --userdir /freqtrade/user_data --logfile /extra_strategies/logs/liststrategies_{{ now | date "20060102" }}.log
      #      # freqtrade list-strategies 
      #   volumeMounts:
      #   - name: configcreds
      #     mountPath: /freqtrade/configcreds
      #   - name: config
      #     mountPath: /freqtrade/config
      #   - name: sqlite
      #     mountPath: /sqlite
      #   - name: extra-strategies
      #     mountPath: /extra_strategies
      #     readOnly: false 
      #   - name: user-data-strategies
      #     mountPath: /freqtrade/user_data/strategies
      #     readOnly: false

      #
      # Main Process, Trading
      # 
      containers:
      # 
      # Debug Container
      #
      - name: debug-container
        image: {{ .Values.image.base }}:{{ .Values.image.tag }}
        command:
        - bash 
        - -c 
        - |
          echo 'Debug container running...'; 
          # sleep 30
          # cat /home/ftuser/.local/lib/python3.12/site-packages/sklearn/utils/_optional_dependencies.py >> /home/ftuser/.local/lib/python3.12/site-packages/sklearn/utils/__init__.py
          # cat /home/ftuser/.local/lib/python3.12/site-packages/sklearn/utils/__init__.py
          while true; do sleep 10; done;
        workingDir: /extra_strategies
        # Set the working directory if needed
        volumeMounts:
        - name: extra-strategies
          mountPath: /extra_strategies
          readOnly: false          
        - name: user-data-strategies
          mountPath: /freqtrade/user_data/strategies
          readOnly: false
        - name: configcreds
          mountPath: /freqtrade/configcreds
        - name: config
          mountPath: /freqtrade/config
        - name: sqlite
          mountPath: /sqlite
      # 
      # Bias 
      #
      - name: bias-container
        image: ghcr.io/dersalvador/ananda/bias:latest
        env:
          - CONFIG_PATH
            value: "/config"
          - COINGECKO_API_KEY: xxx
            value: "my-value"
          - BINANCE_API_KEY: xxx
            value: "my-value"
          - BINANCE_SECRET_KEY: xxx  
            value: "my-value"
        # command:
        # - bash 
        # - -c 
        # - |
        #   echo 'Debug container running...'; 
        #   # sleep 30
        #   # cat /home/ftuser/.local/lib/python3.12/site-packages/sklearn/utils/_optional_dependencies.py >> /home/ftuser/.local/lib/python3.12/site-packages/sklearn/utils/__init__.py
        #   # cat /home/ftuser/.local/lib/python3.12/site-packages/sklearn/utils/__init__.py
        #   while true; do sleep 10; done;
        # workingDir: /extra_strategies
        # Set the working directory if needed
        volumeMounts:
        - name: extra-strategies
          mountPath: /extra_strategies
          readOnly: false          
        - name: user-data-strategies
          mountPath: /freqtrade/user_data/strategies
          readOnly: false
        - name: configcreds
          mountPath: /freqtrade/configcreds
        - name: config
          mountPath: /freqtrade/config
        - name: sqlite
          mountPath: /sqlite

      - name: freqtrade
        image: {{ .Values.image.base }}:{{ .Values.image.tag }}
        env:
          - name: BIAS_ENDPOINT
            value: {{ .Values.bias.endpoint }}
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","sleep 60"]
        command:
        - bash
        - -c
        - |
           # . /home/ftuser/.venv/bin/activate
           # echo pip install python-binance binance_spot binance-connector pywavelets ta ta-lib ta_lib TA-Lib TA_lib multiprocess mailtrap
           # pip install --user python-binance binance_spot binance-connector pywavelets ta ta-lib ta_lib TA-Lib TA_lib multiprocess mailtrap
           echo mkdir -p /freqtrade/user_data/strategies
           mkdir -p /freqtrade/user_data/strategies
           mkdir -p /freqtrade/logs/
           echo cp -R /extra_strategies /freqtrade/user_data/strategies
           cp -R /extra_strategies/* /freqtrade/user_data/strategies
           ls -la /freqtrade/user_data/strategies
           cd /freqtrade
           echo freqtrade trade {{- if .Values.bot.debug }} {{ .Values.bot.debuglevel }} {{- end }} \
           --config  /freqtrade/config/config-{{ .Release.Namespace }}.json  \
           --config /freqtrade/configcreds/configcreds-{{ .Release.Namespace }}.json \
           --logfile /extra_strategies/logs/freqtrade_{{ now | date "20060102" }}.log \
           --strategy {{ .Values.bot.strategy_name }} \
           --db-url sqlite:////sqlite/tradesv3.sqlite 
           echo ""
           echo "Starting Freqtrade"
           echo ""
           freqtrade trade {{- if .Values.bot.debug }} {{ .Values.bot.debuglevel }} {{- end }} \
           --config  /freqtrade/config/config-{{ .Release.Namespace }}.json  \
           --config /freqtrade/configcreds/configcreds-{{ .Release.Namespace }}.json \
           --logfile /extra_strategies/logs/freqtrade_{{ now | date "20060102" }}.log \
           --strategy {{ .Values.bot.strategy_name }} \
           --db-url sqlite:////sqlite/tradesv3.sqlite 
        volumeMounts:
        - name: tmp
          mountPath: /tmp
          readOnly: false       
        - name: extra-strategies
          mountPath: /extra_strategies
          readOnly: false          
        - name: user-data-strategies
          mountPath: /freqtrade/user_data/strategies
          readOnly: false
        - name: configcreds
          mountPath: /freqtrade/configcreds
        - name: config
          mountPath: /freqtrade/config
        - name: sqlite
          mountPath: /sqlite
        ports:
        - name: api
          containerPort: {{ .Values.config.api_server.listen_port }}
      imagePullSecrets:
      - name: deploy-key-gcr
      volumes:
      - name: extra-strategies
        persistentVolumeClaim:
          claimName: freqtrade-extra-strategies   
      - name: user-data-strategies
        persistentVolumeClaim:
          claimName: freqtrade-user-data-strategies   
      - name: tmp
        persistentVolumeClaim:
          claimName: freqtrade-tmp
      - name: configcreds
        configMap:
          name: freqtrade-config-creds-{{ .Release.Namespace }}
      - name: config
        configMap:
          name: freqtrade-config-{{ .Release.Namespace }}
      - name: sqlite
        persistentVolumeClaim:
          claimName: freqtrade-sqlite      
{{- end }}
