---
{{- if .Values.bot.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freqtrade-{{ .Release.Namespace }}
  labels:
    app: freqtrade
    env: production   # Adding a label named env with value production
spec:
  selector:
    matchLabels:
      app: freqtrade-{{ .Release.Namespace }}
  template:
    metadata:
      labels:
        app: freqtrade-{{ .Release.Namespace }}
    spec:
      # nodeName: {{ .Values.kubernetes.nodeNameBackTestingResultsReader }} # pool-dersalvador-y5w2t # pool-dersalvador-ylyw0
      initContainers:
      # - name: add-freqtrade-to-python-path
      #   image: {{ .Values.image.base }}:{{ .Values.image.tag }}
      #   securityContext:
      #     allowPrivilegeEscalation: false
      #     runAsUser: 0
      #   command:
      #   # - bash
      #   # args: ["-c","export FTP="/home/ftuser/.local/lib/python3.11/site-packages\n/extra_strategies"; echo '/freqtrade/freqtrade' > $FTP/freqtrade.pth; echo extended python path with: $(cat $FTP/freqtrade.pth)" ] 
      #   - bash
      #   - -c
      #   - |
      #     export EXPYPATH="/home/ftuser/.local/lib/python3.11/site-packages/freqtrade.pth"
      #     rm -f $EXPYPATH
      #     # WARNING: Dont adjust indention here for file EXPYPATH
      #     cat >>$EXPYPATH <<EOF
      #     /freqtrade/freqtrade
      #     /extra_strategies
      #     EOF
      #     echo Extended python path with: $EXPYPATH
      #     cat $EXPYPATH
      #   volumeMounts:
      #   - name: freqtrade-pythonpath 
      #     subPath: freqtrade.pth
      #     mountPath: /home/ftuser/.local/lib/python3.11/site-packages/freqtrade.pth
      #     readOnly: false
      #   - name: user-data
      #     subPath: freqtrade.pth
      #     mountPath: /home/ftuser/.local/lib/python3.11/site-packages/
      #     readOnly: false          
      - name: take-sqlite-dir-ownership
        image: {{ .Values.image.base }}:{{ .Values.image.tag }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        command:
        - bash
        - -c
        - |
          echo chown -R ftuser:ftuser /sqlite 
          echo chown -R ftuser:ftuser /freqtrade
          echo chown -R ftuser:ftuser /extra_strategies
          echo chmod -R 777 /extra_strategies
          chown -R ftuser:ftuser /sqlite 
          chown -R ftuser:ftuser /freqtrade
          chown -R ftuser:ftuser /extra_strategies
          chmod -R 777 /extra_strategies
          find /sqlite       
        volumeMounts:
        - mountPath: /sqlite
          name: sqlite
{{- if .Values.kubernetes.copyContainer }}          
      - name: copy-strategy-to-default
        image: {{ .Values.image.base }}:{{ .Values.image.tag }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        command: 
        - sh
        - -c
        - |
          set -x
          # echo sed -i '' -e '/freqtrade/d' /home/ftuser/.local/lib/python3.11/site-packages/freqtrade.pth 
          # sed -i '' -e 's/freqtrade/freqtrade\/freqtrade/g' /home/ftuser/.local/lib/python3.11/site-packages/freqtrade.pth 
          for rf in `echo Example_Strat_With_FileLogging MasterMoniGoManiHyperStrategy freqtrade.pth`; do
            echo "find / -name ${rf}* -exec rm -f {}"
            find / -name "${rf}*" -exec rm -f {} ";"
          done
          rm -rf /freqtrade/user_data/strategies/*
          cp -r /extra_strategies/* /freqtrade/user_data/strategies/
          echo Copying strategy {{ .Values.bot.strategy_name }}* to default path
          cp -r /extra_strategies/{{ .Values.bot.strategy_name }}* /freqtrade/user_data/strategies/
          find /freqtrade
        volumeMounts:
        # - name: extra-strategies
        #   mountPath: /extra_strategies
        #   readOnly: false            
        - name: strategies-default
          mountPath: /freqtrade/user_data/strategies
          readOnly: false  
{{- end }}
      - name: freqtrade-list-strategies-{{ .Release.Namespace }}
        image: {{ .Values.image.base }}:{{ .Values.image.tag }}
        command:
        - freqtrade
        args:
        - list-strategies
        # - --recursive-strategy-search   
{{- if .Values.bot.debug }}
        - {{ .Values.bot.debuglevel }}
{{- end }}
        - --config
        - /freqtrade/config/config-{{ .Release.Namespace }}.json
        - --config
        - /freqtrade/configcreds/configcreds-{{ .Release.Namespace }}.json
        - --datadir
        - /freqtrade/user_data/data
        - --userdir
        - /freqtrade/user_data      
        volumeMounts:
        # - name: freqtrade-pythonpath 
        #   subPath: freqtrade.pth
        #   mountPath: /home/ftuser/.local/lib/python3.11/site-packages/freqtrade.pth
        #   readOnly: false
        # - name: user-data
        #   subPath: freqtrade.pth
        #   mountPath: /home/ftuser/.local/lib/python3.11/site-packages/
        #   readOnly: false
        # - name: extra-strategies
        #   mountPath: /extra_strategies
        #   readOnly: false             
        - name: strategies-default
          mountPath: /freqtrade/user_data/strategies
          readOnly: false         
        - name: configcreds
          mountPath: /freqtrade/configcreds
        - name: config
          mountPath: /freqtrade/config
        - name: sqlite
          mountPath: /sqlite          
      - name: freqtrade-strategy-updater-{{ .Release.Namespace }}
        image: {{ .Values.image.base }}:{{ .Values.image.tag }}
        command:
        - freqtrade
        args:
        - strategy-updater
{{- if .Values.bot.debug }}
        - {{ .Values.bot.debuglevel }}
{{- end }}
        - --strategy-list
        - {{ .Values.bot.strategy_name }}
        # - --recursive-strategy-search
        - --log-file 
        - /tmp/freqtrade.log
        - --datadir
        - /freqtrade/user_data/data
        - --userdir
        - /freqtrade/user_data 
        volumeMounts:         
        - name: strategies-default
          mountPath: /freqtrade/user_data/strategies
          readOnly: false
#       - name: freqtrade-test-pairs-{{ .Release.Namespace }}
#         image: {{ .Values.image.base }}:{{ .Values.image.tag }}
#         command:
#         - freqtrade
#         args:
#         - test-pairlist
# {{- if .Values.bot.debug }}
#         - {{ .Values.bot.debuglevel }}
# {{- end }}
#         - --config
#         - /freqtrade/config/config-{{ .Release.Namespace }}.json
#         - --config
#         - /freqtrade/configcreds/configcreds-{{ .Release.Namespace }}.json
#         volumeMounts:
#         # - name: extra-strategies
#         #   mountPath: /extra_strategies
#         #   readOnly: false             
#         - name: strategies-default
#           mountPath: /freqtrade/user_data/strategies
#           readOnly: false
#         - name: configcreds
#           mountPath: /freqtrade/configcreds
#         - name: config
#           mountPath: /freqtrade/config
      containers:
      - name: freqtrade-{{ .Release.Namespace }}
        image: {{ .Values.image.base }}:{{ .Values.image.tag }}
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","sleep 60"]
        command:
        - freqtrade
        args:
        - trade
{{- if .Values.bot.debug }}
        - {{ .Values.bot.debuglevel }}
{{- end }}
        - --config
        - /freqtrade/config/config-{{ .Release.Namespace }}.json
        - --config
        - /freqtrade/configcreds/configcreds-{{ .Release.Namespace }}.json
        - --strategy
        - {{ .Values.bot.strategy_name }}
        - --db-url
        - sqlite:////sqlite/tradesv3.sqlite
        # - --recursive-strategy-search
        - --freqaimodel 
        - {{ .Values.bot.freqaimodel }}
        - --freqaimodel-path 
        - /freqtrade/freqtrade/freqai/prediction_models
        - --log-file 
        - /tmp/freqtrade.log
        - --datadir
        - /freqtrade/user_data/data
        - --userdir
        - /freqtrade/user_data 
        volumeMounts:
        # - name: extra-strategies
        #   mountPath: /extra_strategies
        #   readOnly: false          
        - name: strategies-default
          mountPath: /freqtrade/user_data/strategies
          readOnly: false  
        - name: configcreds
          mountPath: /freqtrade/configcreds
        - name: config
          mountPath: /freqtrade/config
        - name: sqlite
          mountPath: /sqlite
        ports:
        - name: api
          containerPort: {{ .Values.config.api_server.listen_port }}
      imagePullSecrets:
      - name: deploy-key-gcr
      volumes:
      # - name: extra-strategies
      #   persistentVolumeClaim:
      #     claimName: freqtrade-extra-strategies  
      - name: strategies-default
        persistentVolumeClaim:
          claimName: freqtrade-strategies   
      - name: configcreds
        configMap:
          name: freqtrade-config-creds-{{ .Release.Namespace }}
      - name: nfi-hold-trades
        configMap:
          name: freqtrade-nfi-hold-trades-{{ .Release.Namespace }}
      - name: config
        configMap:
          name: freqtrade-config-{{ .Release.Namespace }}
      - name: sqlite
        persistentVolumeClaim:
          claimName: freqtrade-sqlite      
---
{{- end }}
