apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5kaWdpdGFsb2NlYW4uY29tIjp7ImF1dGgiOiJaRzl3WDNZeFgySmpOREl3Wm1OaE9EQm1PREptWkRjMU5qTmlPVEkxWm1RNVpUSXhaR001WVRZNU0yVXpNRGRrTnpjelpUQTNNV0ptTnpBd1l6YzJabU5qTlRJMlpqZzZaRzl3WDNZeFgySmpOREl3Wm1OaE9EQm1PREptWkRjMU5qTmlPVEkxWm1RNVpUSXhaR001WVRZNU0yVXpNRGRrTnpjelpUQTNNV0ptTnpBd1l6YzJabU5qTlRJMlpqZz0ifX19
kind: Secret
metadata:
  name: do-dersalvador-registry
type: kubernetes.io/dockerconfigjson
