apiVersion: v1
kind: ConfigMap
metadata:
  name: freqtrade-nfi-hold-trades-{{ .Release.Namespace }}
  labels:
     app: freqtrade-nfi-hold-trades
data:
  nfi-hold-trades.json: |
{{ toPrettyJson .Values.nostalgiaforinfinity.holdtrades | indent 4 }}

