apiVersion: v1
kind: Service
metadata:
  name: freqtrade-nodeport-{{ .Release.Namespace }}
  labels:
    app: freqtrade-nodeport-{{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: {{ .Values.kubernetes.nodePort }}
    targetPort: api
    nodePort: {{ .Values.kubernetes.nodePort }}
  selector:
    app: freqtrade-{{ .Release.Namespace }}
