apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekE1TVRZdwpOek14TWpkYUZ3MDBNekE1TVRZd056TXhNamRhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDNFBXNWhEbkJtRy91M2hpRzY2bHR2Wm1ncDVnUzlXQ04yd0kyZ2ZpVzZTOUhiR0FYeAo0TzAvb2lqdjNwMHBWMjd3VXNaYlpmTENTRU1rNmdHMytEanZQWDdxc1ZscmIvb1pIT0NPTk9SMndLMENscmgyCjQzUzFjRDE4ckJwaXV2cHdVeWFLNDA3MGl6VjUwQVJLT3piMzZDbk5xa2ROSTlSMU1VQUdOcEJreEhEYjAvSVUKaDZWY29EWGkzWU1ZTGMvbDRQdU9DMElRNzZyQkgyQzh2NUZmMVVQV1BuM2Qvc2RYNlgrTDFBUjR1NVdpZ0drNQpnUWdIZVB2UXlQb3hKVHd5NThISGRsSS82Y2c4SG5DUmx0Q2drMkx4enV0TVJwMTZycUppamNkSnd2cmlTMHgrCjFGeENRZlVRTUt4OTZpTGJvTlJSUUxMNzlSY2hrT2U3T2taRkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlRFa1gwOERXdm5hbUhqM1NOMgpoY0hWeEUrQWlqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFHUlhleGhuQmtTdmNXN0tBTUgwdldiN0IycHUvCjlWZjkwZkJFSW12LzFEL0FqVmtTTVptVU5nNTJnM2ZwMlBYTnh6L1VkdmV3dm5vT2x5VVhENy9od25mYUNkYSsKWE5OZnhkVkRWL1VqQWVZK1hWN2lvQ1VZOTExZllaeWJnTFNnU3kyS3BmVEFUSGFnUFBHeWNBSm55WVdNTUFNNQpYdFFjVVNWOGgrakhMR2ZyWnNzUmNXYS9SMjFuS0FLWlgwK0Q4d1M3elR3RGhkSmhySHhIcmdsMHlkVVhaWklsCjNGU2VDL3cxakIvTThqcnFveDk4eHpuUkxPWlFSY0xXZmEzL25rblZBak50Y2lQM0dhNU54VGdmYyszRDhHNjQKOG03bnRzUnlMQ0luRCtyNUZzWGhZYlk1ZndFd29hemowQWw1aDV0dVVLTlN2Y1ZYZmEva0czbnExUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://4dafc664-7edc-4a09-95f8-d49f6818667e.k8s.ondigitalocean.com
  name: do-ams3-k8s-digital-ocean-dersalvador
contexts:
- context:
    cluster: do-ams3-k8s-digital-ocean-dersalvador
    user: do-ams3-k8s-digital-ocean-dersalvador-admin
  name: do-ams3-k8s-digital-ocean-dersalvador
current-context: do-ams3-k8s-digital-ocean-dersalvador
kind: Config
preferences: {}
users:
- name: do-ams3-k8s-digital-ocean-dersalvador-admin
  user:
    token: dop_v1_f34f2876000d506b489c8a88bb7c7b464e9f9d7f5c92f8999b8d9283a24fecea
